# 2024-05-20

name: Fork & Edit

on:
  workflow_dispatch:
  schedule:
    # "æ—©ä¸Š12ç‚¹ä¸ä¸­åˆ12ç‚¹è¿è¡Œ"
    - cron: "0 0,12 * * *"

jobs:
  Fork-FLITER-list:
    runs-on: ubuntu-latest
    env:
      TZ: 'Asia/Shanghai'
    
    steps: 
    - name: Checkout target repository
      uses: actions/checkout@v4.1.0
      with:
        repository: Amnesiash/ladder_rules_script
        path: ladder-repo

######
    - name: Download files to GeoIP
      run: |
        mkdir -p ladder-repo/Rules/GeoIP
        curl -L -o ladder-repo/Rules/GeoIP/CN_Country.mmdb "https://raw.githubusercontent.com/Masaiki/GeoIP2-CN/release/Country.mmdb"
        curl -L -o ladder-repo/Rules/GeoIP/Global_Country.mmdb "https://raw.githubusercontent.com/Masaiki/GeoIP2-CN/release/Country.mmdb"

######  
    # åŠ è½½å¹¶åˆå¹¶è§„åˆ™:QuantumultX ğŸ§¸
    - name: Download QuantumultX Rules
      run: |
        mkdir -p ladder-repo/Rules/QuantumultX
        # ç›´è¿ä¿®æ­£
        { 
        curl -L "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"
        curl -L "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Direct%2B.list"
        curl -L "https://raw.githubusercontent.com/Amnesiash/ladder_rules_script/main/Rules/Clash/Customized/ManualDirect.list"
        } | tee ladder-repo/Rules/QuantumultX/Direct+.list 

        # ä»£ç†ä¿®æ­£
        { 
        curl -L "https://github.com/Amnesiash/ladder_rules_script/raw/main/Rules/Clash/Customized/Proxy+.list"
        curl -L "https://raw.githubusercontent.com/luestr/ProxyResource/main/Tool/Loon/Plugin/Prevent_DNS_Leaks.plugin"
        } | tee ladder-repo/Rules/QuantumultX/Proxy+.list 
        
        # ä»£ç†åˆ—è¡¨
        {
        curl -L "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
        curl -L "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Proxy.list"
        } | tee ladder-repo/Rules/QuantumultX/Proxy.list

        # ç›´è¿åˆ—è¡¨
        {
        curl -L "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Direct.list"
        curl -L "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
        } | tee ladder-repo/Rules/QuantumultX/Direct.list

        # æœ¬åœ°åœ°å€å’Œè·¯ç”±å™¨ç›´è¿åŸŸå
        curl -L -o ladder-repo/Rules/QuantumultX/LAN.list "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Lan/Lan.list" 

        # æµåª’ä½“
        curl -L -o ladder-repo/Rules/QuantumultX/Streaming!CN.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Streaming/!CN.list"
        curl -L -o ladder-repo/Rules/QuantumultX/StreamingCN.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Streaming/CN.list"
        curl -L -o ladder-repo/Rules/QuantumultX/BiliBili.list "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/BiliBili/BiliBili.list"

        # è‹¹æœæœåŠ¡
        curl -L -o ladder-repo/Rules/QuantumultX/Apple.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Apple/Apple.list"

        # AI
        { 
        curl -L "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/OpenAI/OpenAI.list"
        curl -L "https://raw.githubusercontent.com/Amnesiash/ladder_rules_script/main/Rules/Clash/Customized/AIGC.list"
        curl -L "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Claude/Claude.list"
        curl -L "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Copilot/Copilot.list"
        curl -L "https://raw.githubusercontent.com/luestr/ProxyResource/main/Tool/Loon/Rule/AI.list"
        curl -L "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/AI.list"
        } | tee ladder-repo/Rules/QuantumultX/AI.list

        # å¹¿å‘Šæ‹¦æˆª
        curl -L -o ladder-repo/Rules/QuantumultX/Reject.list "https://adrules.top/qx.conf"

        # WeChat
        curl -L -o ladder-repo/Rules/QuantumultX/WeChat.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/WeChat.list"  

        # Telegram
        curl -L -o ladder-repo/Rules/QuantumultX/Telegram.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Telegram.list"

    # é€‚é… QuantumultX è§„åˆ™
    - name: Edit Rules/QuantumultX
      run: |
        cd ladder-repo/Rules/QuantumultX
        for file in *.list; do
          # ä¸å¤„ç†çš„è§„åˆ™
          if [ "$file" != "Reject.list" ] && [ -f "$file" ]; then
            # é€‚é…
            sed -i -e 's/, /,/g' \
                   -e 's/,REJECT$//g' \
                   -e 's/,DIRECT$//g' \
                   -e 's/,PROXY$//g' \
                   -e 's/,Apple$//g' \
                   -e 's/,Direct$//g' \
                   -e 's/,China$//g' \
                   -e 's/,OpenAI$//g' \
                   -e 's/,Proxy$//g' \
                   -e 's/,GlobalMedia$//g' \
                   -e 's/,Lan$//g' \
                   -e 's/,reject$//g' \
                   -e 's/,direct$//g' \
                   -e 's/,proxy$//g' \
                   -e 's/DOMAIN,/HOST,/g' \
                   -e 's/DOMAIN-/HOST-/g' \
                   -e 's/IP-CIDR6,/IP6-CIDR,/g' \
                   -e 's/,no-resolve//g' \
                   -e 's/,extended-matching$//g' \
                   -e '/\(OR\|AND\|NOT\|PROCESS-NAME\|URL-REGEX\),/ s/^/#/' \
                   -e 's| \{1,\}//.*$||' \
                   -e '/# /d' \
                   -e 's/\/\/.*$//' \
                   "$file"
          else
            echo "$file not found."
          fi
        done

    # å»é‡æ’åº QuantumultX
    - name: Remove QuantumultX rules duplicates å’Œ lines
      run: |
        cd ladder-repo/Rules/QuantumultX
        shopt -s nullglob  # é¿å…æ²¡æœ‰åŒ¹é…çš„æ–‡ä»¶æ—¶ä¿ç•™åŸå§‹é€šé…ç¬¦
        for file in *.list; do
          if [ "$file" != "Reject.list" ] && [ -f "$file" ]; then
            # åˆ†æµè§„åˆ™çš„æ’åº
            sort -o "$file" "$file"
            awk '
              /^HOST,/ { host[++n] = $0; next }
              /^HOST-SUFFIX,/ { suffix[++m] = $0; next }
              /^HOST-KEYWORD,/ { keyword[++p] = $0; next }
              /^HOST-WILDCARD,/ { wildcard[++r] = $0; next }
              /^USER-AGENT,/ { useragent[++r] = $0; next }
              /^IP-CIDR,/ { cidr[++q] = $0; next }
              /^IP6-CIDR,/ { cidr6[++r] = $0; next }
              END {
                  for (i = 1; i <= n; i++) print host[i]
                  for (i = 1; i <= m; i++) print suffix[i]
                  for (i = 1; i <= p; i++) print keyword[i]
                  for (i = 1; i <= r; i++) print wildcard[i]
                  for (i = 1; i <= r; i++) print useragent[i]
                  for (i = 1; i <= q; i++) print cidr[i]
                  for (i = 1; i <= r; i++) print cidr6[i]
              }
            ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
            # åˆ é™¤é‡å¤çš„è§„åˆ™
            awk '!seen[$0]++ && NF' "$file" > temp && mv temp "$file"
          else
            echo "$file not found."
          fi
        done        

######  
    # åŠ è½½å¹¶åˆå¹¶è§„åˆ™:Clash ğŸ§¸
    - name: Download Clash Rules
      run: |
        mkdir -p ladder-repo/Rules/Clash
        # ç›´è¿ä¿®æ­£
        { 
        curl -L "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list"
        curl -L "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Direct%2B.list"
        curl -L "https://raw.githubusercontent.com/Amnesiash/ladder_rules_script/main/Rules/Clash/Customized/ManualDirect.list"
        } | tee ladder-repo/Rules/Clash/Direct+.list 

        # ä»£ç†ä¿®æ­£
        { 
        curl -L "https://github.com/Amnesiash/ladder_rules_script/raw/main/Rules/Clash/Customized/Proxy+.list"
        curl -L "https://raw.githubusercontent.com/luestr/ProxyResource/main/Tool/Loon/Plugin/Prevent_DNS_Leaks.plugin"
        } | tee ladder-repo/Rules/Clash/Proxy+.list 
        
        # ä»£ç†åˆ—è¡¨
        {
        curl -L "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list"
        curl -L "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Proxy.list"
        } | tee ladder-repo/Rules/Clash/Proxy.list

        # ç›´è¿åˆ—è¡¨
        {
        curl -L "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Direct.list"
        curl -L "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list"
        } | tee ladder-repo/Rules/Clash/Direct.list

        # æœ¬åœ°åœ°å€å’Œè·¯ç”±å™¨ç›´è¿åŸŸå
        curl -L -o ladder-repo/Rules/Clash/LAN.list "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list" 

        # æµåª’ä½“
        curl -L -o ladder-repo/Rules/Clash/Streaming!CN.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Streaming/!CN.list"
        curl -L -o ladder-repo/Rules/Clash/StreamingCN.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Streaming/CN.list"
        curl -L -o ladder-repo/Rules/Clash/BiliBili.list "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list"

        # è‹¹æœæœåŠ¡
        curl -L -o ladder-repo/Rules/Clash/Apple.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Apple/Apple.list"

        # AI
        { 
        curl -L "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list"
        curl -L "https://raw.githubusercontent.com/Amnesiash/ladder_rules_script/main/Rules/Clash/Customized/AIGC.list"
        curl -L "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list"
        curl -L "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list"
        curl -L "https://raw.githubusercontent.com/luestr/ProxyResource/main/Tool/Loon/Rule/AI.list"
        curl -L "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/AI.list"
        } | tee ladder-repo/Rules/Clash/AI.list

        # å¹¿å‘Šæ‹¦æˆª
        curl -L -o ladder-repo/Rules/Clash/Reject.list "https://adrules.top/adrules_domainset.txt"

        # WeChat
        curl -L -o ladder-repo/Rules/Clash/WeChat.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/WeChat.list"  

        # Telegram
        curl -L -o ladder-repo/Rules/Clash/Telegram.list "https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Telegram.list"  

    # é€‚é… Clash è§„åˆ™
    - name: Edit Rules/Clash
      run: |
        cd ladder-repo/Rules/Clash
        for file in *.list; do
          # ä¸å¤„ç†çš„è§„åˆ™
          if [ "$file" != "Reject.list" ] && [ -f "$file" ]; then
            # é€‚é…
            sed -i -e 's/, /,/g' \
                   -e 's/;/# /g' \
                   -e 's/host,/HOST,/g' \
                   -e 's/host-/HOST-/g' \
                   -e 's/-suffix/-SUFFIX/g' \
                   -e 's/-keyword/-KEYWORD/g' \
                   -e 's/ip-cidr/IP-CIDR/g' \
                   -e 's/geoip/GEOIP/g' \
                   -e 's/HOST,/DOMAIN,/g' \
                   -e 's/HOST-/DOMAIN-/g' \
                   -e 's/IP6-CIDR,/IP-CIDR6,/g' \
                   -e 's/,REJECT$//g' \
                   -e 's/,DIRECT$//g' \
                   -e 's/,PROXY$//g' \
                   -e 's/,reject$//g' \
                   -e 's/,direct$//g' \
                   -e 's/,proxy$//g' \
                   -e 's/,extended-matching$//g' \
                   -e '/\(OR\|AND\|NOT\|USER-AGENT\|URL-REGEX\|IP-ASN\),/ s/^/#/' \
                   -e '/# /d' \
                   -e 's/\/\/.*$//' \
                   "$file"
          else
            echo "$file not found."
          fi
        done

    # å»é‡æ’åº Clash
    - name: Remove Clash rules duplicates å’Œ lines
      run: |
        cd ladder-repo/Rules/Clash
        shopt -s nullglob  # é¿å…æ²¡æœ‰åŒ¹é…çš„æ–‡ä»¶æ—¶ä¿ç•™åŸå§‹é€šé…ç¬¦
        for file in *.list; do
          if [ "$file" != "Reject.list" ] && [ -f "$file" ]; then
            # åˆ†æµè§„åˆ™çš„æ’åº
            sort -o "$file" "$file"
            awk '
              /^DOMAIN,/ { domain[++n] = $0; next }
              /^DOMAIN-SUFFIX,/ { suffix[++m] = $0; next }
              /^DOMAIN-KEYWORD,/ { keyword[++p] = $0; next }
              /^IP-CIDR,/ { cidr[++q] = $0; next }
              /^IP-CIDR6,/ { cidr6[++r] = $0; next }
              /^PROCESS-NAME,/ { process[++r] = $0; next }
              END {
                  for (i = 1; i <= n; i++) print domain[i]
                  for (i = 1; i <= m; i++) print suffix[i]
                  for (i = 1; i <= p; i++) print keyword[i]
                  for (i = 1; i <= q; i++) print cidr[i]
                  for (i = 1; i <= r; i++) print cidr6[i]
                  for (i = 1; i <= r; i++) print process[i]
              }
            ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
            # åˆ é™¤é‡å¤çš„è§„åˆ™
            awk '!seen[$0]++ && NF' "$file" > temp && mv temp "$file"
          else
            echo "$file not found."
          fi
        done

######
    - name: Add å’Œ Commits
      run: |
        cd ladder-repo
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto Update $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push origin HEAD
        else
          echo "No changes to commit."
        fi

    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2
